services:
  - type: web
    name: heatnvector
    runtime: static
    repo: https://github.com/Omar-Galsen/HeatnVector
    branch: main
    buildCommand: mkdir -p public && cp index.html public/index.html
    staticPublishPath: ./public
